management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    database: POSTGRESQL
    show-sql: 'true'
    properties:
      hibernate:
        show_sql: 'true'
  application:
    name: cliente
  datasource:
    driverClassName: org.postgresql.Driver
    password: pass
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    platform: postgres
  sleuth:
    sampler:
      probability: '1.0'
  cloud:
    config:
      server:
        bootstrap: 'true'
      uri: http://localhost:8890
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  error:
    include-binding-errors: always
    include-message: always
  port: '8085'
